### ISSUE TITLE
UCD-Agent offline after container restart

### ISSUE THREAD

**Issue by s3n29t** [IBM-UrbanCode/UCD-Docker-Images#9]
If I do a restart of the UDC Agent Container, then the previous Agent connection in UDC Deploy Server is offline and a new agent is automatically registered. In Description with the message "Error: New name agent-0f475ec59174 is already in use by another agent". Is there no way to connect the initially created agent?

Thanks for helping.

Regards
Peter

![ibm_urbancode_deploy__ressourcen](https://cloud.githubusercontent.com/assets/19804538/23253130/ad2ce172-f9b3-11e6-8b73-d6bb86fa478b.jpg)

**Comment by nhmathis** [comment]
Hi @s3n29t,

This issue is being resolved with pull request #11!

-Nick

**Comment by nhmathis** [comment]
Today [DockerHub UCD v6.2.5.2.929926 images](https://hub.docker.com/r/ibmcom/ucds) have been released and PR #11 has been merged. Now you can specify an AGENT_NAME environment variable to persist agents between `docker` starts and stops.

**Comment by LongLiveCHIEF** [comment]
This needs to be re-opened. #11 did not fix this. The `agentStart.sh` file used for the container entrypoint removes the `agent.id` property as the very first step. 

This causes a new agentID to be generated on each container start, which still triggers the autogeneration of a new agent resource using `agent-[agent.id]` as the agent name in the uc server resource list.

**Comment by nhmathis** [comment]
If you uncomment line 24 in the docker-compose.yaml file and then rebuild the docker-compose containers, does that resolve your issue? You can give the agent any name you would like.

Uncomment this line: 
https://github.com/IBM-UrbanCode/UCD-Docker-Images/blob/222ae2de6be40fe21ecfe1f876c20c05f60b20b3/compose/Deploy/docker-compose.yaml#L24

By default, an agent without an id will generate a new id on each agent start time. Therefore, by giving it a name, it will have an ID to associate with it's configuration.
